import '../styles/globals.css'
import '../styles/fonts.css'
// import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import {NextAuthProvider} from "@/app/provider";

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: any
}) {
  return (
    <html lang="en">
      <body>
      <NextAuthProvider session={session}>
          <Header/>
          <ToastContainer autoClose={2000} theme="colored"/>
          {children}
      </NextAuthProvider>
      </body>
    </html>
  )
}
